# Concept of Batches, Layers, and Objects

In [1]:
import numpy as np 

# 1)- Shape Error

We have had an input with four features and one sample in last session. Now, we shall use input of 4 features with 3 samples. 

Samples refer to rows and features refer to columns.

In [2]:
inputs=[[1.0 , 2.0 , 3.0 , 2.5],
        [2.0, 5.0 , -1.0 , 2.0],
        [-1.5 , 2.7 , 3.3 , -0.8]]

In [3]:
inputs

[[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

In [4]:
weights=[[0.2 , 0.8 , -0.5, 1.0],
        [0.5 , -0.91 , 0.26 , -0.5 ],
        [-0.26 , -0.27 , 0.17 , 0.87]]

In [5]:
weights

[[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

In [6]:
biases=[2,3,0.5] # three biase values again three weight sample i.e 3 rows in weight

In [7]:
output=np.dot(inputs, weights) + biases

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

we get a shape error

Let's try to change dot product. We shall use weights.inputs

In [8]:
output=np.dot(weights, inputs) + biases

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

We still get shape error.

Reason is how dot product works. 

- https://betterexplained.com/articles/vector-calculus-understanding-the-dot-product/

# 2)- Solution of shape error

We can solve this by aligning rows and columns in right order. We can take transpose.



In [9]:
%%time
output=np.dot(inputs , np.array(weights).T) + biases

CPU times: user 2.23 ms, sys: 1.56 ms, total: 3.79 ms
Wall time: 2.54 ms


In [10]:
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

# 3)-Adding Layer

creating weights2 and biases 2

In [11]:
inputs=[[1.0 , 2.0 , 3.0 , 2.5],
        [2.0, 5.0 , -1.0 , 2.0],
        [-1.5 , 2.7 , 3.3 , -0.8]]

In [12]:
weights1=[[0.2 , 0.8 , -0.5, 1.0],
        [0.5 , -0.91 , 0.26 , -0.5 ],
        [-0.26 , -0.27 , 0.17 , 0.87]]

In [13]:
biases1=[2,3,0.5]

Above code shows first layer.

In [14]:
weights2=[[0.1, -0.14 , 0.5],
        [-0.5, 0.12 ,-0.33],
        [-0.44 , 0.73 , -0.13]]

In [15]:
biases2=[-1 , 2, -0.5]

In [16]:
%%time
layer1_output = np.dot(inputs, np.array(weights1).T) + biases1
layer1_output

CPU times: user 75 µs, sys: 6 µs, total: 81 µs
Wall time: 78.7 µs


array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [17]:
%%time
layer2_output = np.dot(layer1_output , np.array(weights2).T) + biases2
layer2_output

CPU times: user 75 µs, sys: 9 µs, total: 84 µs
Wall time: 79.2 µs


array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

# 4)-Create objects

as a way of writing long code for given layers

In [18]:
# input
np.random.seed(42) # for having same output keep random seed constant.
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [19]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [20]:
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

In [21]:
layer1.forward(X)
print(layer1.output)

[[-0.27675317 -0.09091057  0.36940631 -0.74258198 -0.7854546 ]
 [-0.08384138  0.6059603   0.55190831  0.07959199  0.11448039]
 [-0.24566894  0.37446278  0.16476186 -0.91395312 -0.27462437]]


In [22]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.07136211  0.01831101]
 [-0.05427832 -0.0786683 ]
 [ 0.07924331 -0.07230373]]


In next session, we shall disucuss how hidden layer architect looks like , what are activation functions are.